### PR TITLE
Add support for new driver discovery mechanism.

### PR DESCRIPTION
**Pull request by danielballan**
See intake/intake#236

### CODE REVIEW

**Comment by danielballan** [comment]
One of the three Travis-CI builds failed, looks related to `CONDA_UPLOAD` not this PR.

**Comment by martindurant** [comment]
A few of the older packages still use conda-build and upload during testing, but I see no benefit in it - better off installing packages in the CI script and running pytest directly.

**Comment by danielballan** [comment]
Should I add a commit here ripping that out then?

**Comment by martindurant** [comment]
Yes I think so, and the same with the others that have this leftover. We can talk separately and I can tell you what the original idea had been.

**Pull request merged**
